### ISSUE TITLE
Queries & Commands in Domain level

### ISSUE THREAD

**Issue by ddenysov** [somnambulist-tech/accounts-service-skeleton#2]
https://github.com/somnambulist-tech/accounts-service-skeleton/blob/3bdfcde5803c7fabd6982bf6431161931e972a40/src/Users/Domain/Queries/FindUsers.php#L1

Hello again :)

Just curious why Queries and Commands are inside Domain level ? Why not Application ?

**Comment by dave-redfern** [comment]
Good question!

I think of them as artifacts of the domain, however they can live in the application layer just as easily. To be honest, I am not 100% sure what makes most sense so I am consistent in keeping them in the domain - after all it is the implementation that varies and not necessarily the query / command itself.

At the end of the day: it is up to you to make that decision. If you prefer them in an `Application` namespace with the handlers, then that is fine - just be consistent! If you do this in one context, do this for _ALL_ contexts so it is not confusing to someone looking at the code.
