### ISSUE TITLE
Flush method for entities

### ISSUE THREAD

**Issue by ddenysov** [somnambulist-tech/accounts-service-skeleton#3]
https://github.com/somnambulist-tech/accounts-service-skeleton/blob/3bdfcde5803c7fabd6982bf6431161931e972a40/src/Users/Infrastructure/Persistence/Repositories/UserRepository.php#L28

Where is flush() method should be called ?

**Comment by dave-redfern** [comment]
Commands are dispatched through the command bus that is (should be!) setup using `doctrine_transaction` middleware in the Messenger configuration. This way all commands are individually wrapped in a transaction, so adding flush in the repositories is not needed. See https://github.com/somnambulist-tech/domain/blob/master/docs/messenger.md for the recommended default configuration.

To account for cases where someone does not use the command bus, you could add the flush() here - or if you do not want to use the middleware on the bus itself, then you would have to.

Again: this was a decision I made and it's entirely your choice if you adopt this. Just be aware of the pros and cons. For what it is worth: I think I may adopt explicitly calling flush() when I update this project (I am currently in the process of overhauling it for Symfony 6.2 + new version of my other libraries) to avoid issues of mis-use.
